"""add eagler_dafaults

Revision ID: 9fd95be1c242
Revises: 1aa5b911ca00
Create Date: 2022-03-06 18:17:09.324608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd95be1c242'
down_revision = '1aa5b911ca00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
