"""tables

Revision ID: bdbc51160e3b
Revises: 
Create Date: 2022-03-06 12:35:32.414009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdbc51160e3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_together_room',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('film_work_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('owner_uuid', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('owner_uuid')
    )
    op.create_table('movie_together_room_user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('room_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['room_uuid'], ['movie_together_room.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_uuid', 'room_uuid', name='unique_room_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_together_room_user')
    op.drop_table('movie_together_room')
    # ### end Alembic commands ###
