services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    ports:
      - 22181:2181
    env_file:
      - .env
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    env_file:
      - .env
    restart: unless-stopped

#  topics_init_python:
#    container_name: topics_init_python
#    depends_on:
#      - kafka
#    build:
#      context: ./kafka
#    volumes:
#      - ./kafka:/app/
#    restart: on-failure
